myclub_project/events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('', views.IndexView, name='index'),
    path('<int:event_id>/', views.detail, name='detail'),
]

myclub_project/myclub_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('events/', include('events.urls')),
    path('admin/', admin.site.urls),
]

myclub_project/events/models.py
# myclub_project\events\models.py

from django.db import models

class Venue(models.Model):

    name = models.CharField('Venue Name', max_length=120)
    address = models.CharField(max_length=300)
    zip_code = models.CharField('Zip/Post Code', max_length=12)
    phone = models.CharField('Contact Phone', max_length=20)
    web = models.URLField('Web Address')
    email_address = models.EmailField('Email Address')

    def __str__(self):
        return self.name


class MyclubUser(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField('User Email')

    def __str__(self):
        return self.first_name + " " + self.last_name

class Event(models.Model):
    name = models.CharField('Event Name', max_length=120)
    event_date = models.DateTimeField('Event Date')
    venue = models.CharField(max_length=120)
    manager = models.CharField(max_length = 60)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

myclub_project/events/views.py
from django.shortcuts import get_object_or_404, render

from .models import Event


def IndexView(request):
    event_list = Event.objects.all()
    context = {'event_list': event_list}
    return render(request, 'events/index.html', context)

def detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    return render(request, 'events/detail.html', {'event': event})

# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)

# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)

myclub_project/events/templates/events/detail.html
<h2>{{ event.name }}</h2>
<p>{{ event.event_date }}</p>
<p>{{ event.venue }}</p>
<p>{{ event.manager }}</p>
<p>{{ event.description }}</p>

myclub_project/events/templates/events/index.html
{% block content %}

  {% if event_list %}
    <h2> Events List </h2>
    <ul>
      {% for event in event_list %}
      <li><a href="{% url 'events:detail' event.id %}" style="color:black">{{ event.name|title }}</a></li>
      {% endfor %}
    </ul>

  {% else %}

    <p>No wiki pages are available.</p>

  {% endif %}

{% endblock %}